trigger:
- main

pr:
- main

variables:
- group: Playwright Variables

stages:
- stage: WaitThenRunTests
  displayName: "Wait 1 minutes, then run Playwright"
  jobs:
  - job: WaitJob
    displayName: "Delay 1 minutes (agentless)"
    pool: server
    steps:
      - task: Delay@1
        inputs:
          delayForMinutes: '1'

  - job: PlaywrightTests
    displayName: "Run Playwright Tests"
    dependsOn: WaitJob
    pool:
      name: Self Hosted Pool
    steps:
      - task: UseNode@1
        inputs:
          version: '22'
        displayName: 'Install Node.js'

      - script: npm ci
        displayName: 'npm ci'
      - script: npx playwright install --with-deps
        displayName: 'Install Playwright browsers'
      - script: npx playwright test
        displayName: 'Run Playwright tests'
        env:
          LOGGEDIN_PASSWORD: $(LOGGEDIN_PASSWORD)
          APPINSIGHTS_CONNECTION_STRING: $(APPINSIGHTS_CONNECTION_STRING)
          AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          searchFolder: 'test-results'
          testResultsFormat: 'JUnit'
          testResultsFiles: 'e2e-junit-results.xml'
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: 'My End-To-End Tests'
        condition: succeededOrFailed()
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: playwright-report
          artifact: playwright-report
          publishLocation: 'pipeline'
        condition: succeededOrFailed()